using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace Problem2
{
    class Program
    {
        /* This function is a bruteforce method of generating the Fibonacci number sequence
         * I start with the inital starting numbers 1 and 2, and then go through a while
         * loop until the current number reaches the maximum number. Since in the problem
         * we only want to add up the sum of the even numbers I first check to see if the 
         * lower of the two numbers is even and then generate the next number in the sequence
         * 
         * The runtime for this will be O(n) where n is the number of Fibonacci numbers in
         * the sequence before the "max" value. Since we are having to generate each 
         * Fibonacci number in order to see if it is even or not, the runtime will be O(n)
         */
        static int Fibonacci(int max)
        {
            int sum = 0;
            int newTerm = 2;
            int prevTerm = 1;
            int temp = 0;

            try
            {
                // Loop until the smaller of the two numbers is greater than the max limit
                while (prevTerm < max && newTerm < int.MaxValue)
                {
                    // Check to see if the smaller of the two numbers is even
                    if (prevTerm % 2 == 0)
                    {
                        sum += prevTerm;
                    }
                    // Generate the next number in the sequence using a temp variable to
                    // save on computations.
                    temp = newTerm;
                    newTerm = newTerm + prevTerm;
                    prevTerm = temp;
                }

                return sum;
            }
            catch (OverflowException)
            {
                return -1;
            }
            catch (Exception)
            {
                return -2;
            }
        }

        static void Main(string[] args)
        {
            int num = 2;
            Console.WriteLine("Problem " + num + " of Project Euler\n" +
                                "https://projecteuler.net/problem=" + num + "\n" +
                                "\n" +
                                "Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:\n" +
                                "1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...\n" +
                                "By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.\n" +
                                "\n" +
                                "Here is the answer to 4000000:");

            int results = Fibonacci(4000000);

            if (results >= 0)
            {
                Console.WriteLine(results);
            }
            else if (results == -1)
            {
                Console.WriteLine("Overflow Exception was encountered. The Fibonacci number exceeded the Max Value for an Int.");
            }
            else
            {
                Console.WriteLine("Unexpected Exception occured...");
            }
        }
    }
}






